export type {
  Estate,
  DeceasedPerson,
  DomicileStatus,
  MaritalStatus,
  ResidenceDetails,
  DownsizingDetails,
  PredecessorEstate,
  Liability,
  LiabilityType,
  Beneficiary,
  BeneficiaryRelationship,
  InheritanceType,
  SpecificBequest,
} from './estate';
export type {
  Asset,
  BaseAsset,
  PropertyAsset,
  FinancialAsset,
  BusinessAsset,
  BusinessType,
  BprEligibility,
  AgriculturalAsset,
  AprEligibility,
  PersonalAsset,
  TrustInterestAsset,
  TrustType,
  JointOwnership,
} from './assets';
export type {
  LifetimeGift,
  BaseGift,
  PotentiallyExemptTransfer,
  ChargeableLifetimeTransfer,
  ExemptGift,
  ExemptionType,
  GiftRecipient,
} from './gifts';
export type {
  CalculationResult,
  CalculationError,
  CalculationOutcome,
  TaxSummary,
  CalculationBreakdown,
  EstateValuationBreakdown,
  ReliefBreakdown,
  ReliefDetail,
  ExemptionBreakdown,
  ThresholdBreakdown,
  TaxBreakdown,
  GiftAnalysis,
  GiftSummary,
  ChargeableGiftSummary,
  Warning,
  AuditEntry,
  ValidationError,
} from './results';
